version: "3.7"
services:
  gazpar2mqtt:
    container_name: gazpar2mqtt
    image: yukulehe/gazpar2mqtt:latest
    tty: true
    restart: unless-stopped
    environment:
      GRDF_USERNAME=gazou@email.com
      GRDF_PASSWORD=password
      MQTT_HOST=host
      TZ=Europe/Paris
      # Optional:
      #SCHEDULE_TIME: '06:30'
      #MQTT_PORT: '1883'
      #MQTT_TOPIC: 'gazpar'
      #MQTT_CLIENTID: 'gazou'
      #MQTT_USERNAME: 'myMqttUsername'
      #MQTT_PASSWORD: 'myMqttPassword'
      #MQTT_QOS: '1'
      #MQTT_RETAIN: 'True'
      #STANDALONE_MODE: 'False'
      #HASS_DISCOVERY: 'True'
      #HASS_PREFIX: 'homeassistant'
